version: "3"
services:
  app:
    image: node:13.2.0-alpine3.10
    working_dir: /var/www/node
    volumes:
    - .:/var/www/node
    ports:
    - 3000:3000
    command: sh -c "npm install; npm start"
